#!/hint/sh

# Set the theme
--theme=TwoDark

# Use italic text on the terminal (not supported on all terminals)
--italic-text=always

# Use C++ syntax (instead of C) for .h header files
--map-syntax h:C++

# Open .clang-format files as YAML files
--map-syntax .clang-format:YAML

# Open cargo config files as TOML files
--map-syntax **/*cargo/config:TOML
