#!/hint/sh

# Don't draw any additional decoration
--plain

# Set the theme
--theme=TwoDark

# Use C++ syntax (instead of C) for .h header files
--map-syntax h:C++

# Open .clang-format files as YAML files
--map-syntax .clang-format:YAML

# Open cargo config files as TOML files
--map-syntax **/*cargo/config:TOML

# Open tmux config file with bash syntax
--map-syntax .tmux.conf:'Bourne Again Shell (bash)'

# Open ebuild files used in gentoo with bash syntax
--map-syntax *.ebuild:'Bourne Again Shell (bash)'
