[build]
rustflags = [
    "-C", "target-cpu=native"
]

[alias]
rr = "run --release"
tr = "test --release"
to = "test -- --nocapture"
ti = "test -- --include-ignored"
d = "doc --no-deps"

[profile.profiling]
inherits = "release"
debug = true
